[phases.setup]
cmds = [
   "apt-get update -y",                     
    "apt-get install -y build-essential perl", 
    "cpan HTTP::Server::Brick"   
]

[phases.build]
cmds = []

[phases.start]
cmd = "perl -MHTTP::Server::Brick -e 'HTTP::Server::Brick->new(port => $PORT)->mount(\"/\" => {path => \"index.pl\"})->start'"
