[phases.setup]
cmds = [
    "apt-get update -y",                      
    "apt-get install -y build-essential perl",  
    "cpan HTTP::Server::Simple::CGI"         
]

[phases.build]
cmds = []

[phases.start]
cmd = "perl app.pl" 
