[phases.setup]
cmds = [
    "cpan HTTP::Server::Brick" # Instala el módulo HTTP::Server::Brick
]

[phases.build]
cmds = []

[phases.start]
cmd = "perl -MHTTP::Server::Brick -e 'HTTP::Server::Brick->new(port => $PORT)->mount(\"/\" => {path => \"index.pl\"})->start'"

